### ISSUE TITLE
AttributeError: 'stringzilla.Strs' object has no attribute 'extend'

### ISSUE THREAD

**Issue by h4RkhW8t53e** [ashvardanian/usearch-molecules#4]
Hi again,
Just to let you know; this happens in prep_parquet.py while trying to read smiles from multiple files as in REAL. 
Am I doing it wrong or the API has changed?

    lines.extend(file_lines)
    ^^^^^^^^^^^^
AttributeError: 'stringzilla.Strs' object has no attribute 'extend'

**Comment by ashvardanian** [comment]
@h4RkhW8t53e, the StringZilla API has changed. Can you check if it works with StringZilla v2 or v1? If so, we need to patch the `requirements.txt`.

**Comment by h4RkhW8t53e** [comment]
Thank you for your quick reply! prep_parquet.py works with StringZilla v1 (1.2.2) and 
file = Str(str(File(os.path.join(dir, filename)))) instead of file = Str(File(os.path.join(dir, filename))).

**Comment by ashvardanian** [comment]
Great, thank you @h4RkhW8t53e! Can you please patch those?

**Comment by h4RkhW8t53e** [comment]
Hi, a patch is attached. Would it be possible to update prep_parquet.py and prep_smiles.py to use Stringzilla v3 instead?
[sz_v1.patch](https://github.com/ashvardanian/usearch-molecules/files/14635552/sz_v1.patch)

**Comment by ashvardanian** [comment]
Hi @h4RkhW8t53e! Any chance you could submit it as a PR? 

Sure, I will look into upgrade options soon, when I publish the new embeddings you've suggested - already working on them 🤗
